# Generated by Django 5.2.9 on 2026-01-06 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpurchase',
            name='tipo_pagamento',
            field=models.CharField(choices=[('CREDITO', 'Crédito'), ('DEBITO', 'Débito'), ('PIX', 'Pix'), ('DINHEIRO', 'Dinheiro')], default='CREDITO', max_length=10),
        ),
        migrations.AlterField(
            model_name='cardpurchase',
            name='cartao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='core.card'),
        ),
    ]
