# Generated by Django 5.2.9 on 2026-01-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_household'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardpurchase',
            name='cartao',
        ),
        migrations.RemoveField(
            model_name='cardpurchase',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='cardpurchase',
            name='user',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='CardPurchase',
        ),
    ]
