# Generated by Django 5.2.9 on 2026-01-17 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_cardpurchase_cartao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringexpense',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='recurringexpense',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recurringpayment',
            name='expense',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='RecurringExpense',
        ),
        migrations.DeleteModel(
            name='RecurringPayment',
        ),
    ]
