# Generated by Django 5.2.9 on 2026-01-16 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_household"),
        ("finance", "0002_card_cardpurchasegroup_importbatch_importitem_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestmentAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("institution", models.CharField(blank=True, max_length=120)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_investment_accounts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investment_accounts",
                        to="core.household",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InvestmentSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                ("balance", models.DecimalField(decimal_places=2, max_digits=14)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="finance.investmentaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_investment_snapshots_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investment_snapshots",
                        to="core.household",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month"],
            },
        ),
        migrations.AddConstraint(
            model_name="investmentaccount",
            constraint=models.UniqueConstraint(
                fields=("household", "name"), name="unique_investment_account_household"
            ),
        ),
        migrations.AddIndex(
            model_name="investmentsnapshot",
            index=models.Index(
                fields=["household", "year", "month"],
                name="investment_household_ym_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="investmentsnapshot",
            index=models.Index(
                fields=["account", "year", "month"], name="investment_account_ym_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="investmentsnapshot",
            constraint=models.UniqueConstraint(
                fields=("account", "year", "month"),
                name="unique_investment_snapshot_account_month",
            ),
        ),
    ]
