# Generated by Django 5.2.9 on 2026-01-16 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_investmentaccount_investmentsnapshot_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="importitem",
            old_name="installments_count",
            new_name="installments_total",
        ),
        migrations.RenameField(
            model_name="importitem",
            old_name="date",
            new_name="purchase_date",
        ),
        migrations.AddField(
            model_name="card",
            name="closing_day",
            field=models.PositiveIntegerField(
                default=25,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="due_day",
            field=models.PositiveIntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
        migrations.AddField(
            model_name="cardpurchasegroup",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cardpurchasegroup",
            name="statement_month",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cardpurchasegroup",
            name="statement_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="statement_month",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="statement_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importitem",
            name="installments_current",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importitem",
            name="purchase_flag",
            field=models.CharField(default="UNKNOWN", max_length=20),
        ),
        migrations.AddField(
            model_name="importitem",
            name="purchase_prefix_raw",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="importitem",
            name="statement_month",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="importitem",
            name="statement_year",
            field=models.PositiveIntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="installment",
            name="statement_month",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="installment",
            name="statement_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
