# Generated by Django 5.0.6 on 2024-07-15 12:00

from django.db import migrations
from finance.utils import build_installment_logical_key


def forwards_func(apps, schema_editor):
    """
    Backfills the logical_key for existing CardPurchaseGroup records
    that were created before this field was introduced.
    """
    CardPurchaseGroup = apps.get_model('finance', 'CardPurchaseGroup')
    db_alias = schema_editor.connection.alias

    # Select only groups that need backfilling
    groups_to_update = CardPurchaseGroup.objects.using(db_alias).filter(logical_key__isnull=True)

    print(f"\\n  Found {groups_to_update.count()} purchase groups to backfill with a logical_key.")

    for group in groups_to_update:
        # Ensure all required data is present before attempting to build the key
        if group.description and group.purchase_date and group.total_amount is not None and group.installments_count is not None:
            try:
                group.logical_key = build_installment_logical_key(
                    description=group.description,
                    purchase_date=group.purchase_date,
                    amount=group.total_amount,
                    installments_total=group.installments_count
                )
                # Save only the updated field to avoid side-effects
                group.save(update_fields=['logical_key'])
            except Exception as e:
                print(f"    - Could not update group {group.id} ('{group.description}') due to an error: {e}")
        else:
            print(f"    - Skipping group {group.id} ('{group.description}') due to missing data.")


def reverse_func(apps, schema_editor):
    """
    The reverse operation is a no-op. The logical_key will be left as is.
    There is no harm in leaving the keys populated.
    """
    print("\\n  No reverse operation for backfilling logical_keys.")
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_cardpurchasegroup_logical_key'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
