from django.urls import path

from . import views

app_name = "finance"

urlpatterns = [
    path("cards/", views.card_list, name="cards"),
    path("cards/new/", views.card_create, name="card-create"),
    path("cards/<int:pk>/edit/", views.card_edit, name="card-edit"),
    path("cards/<int:pk>/delete/", views.card_delete, name="card-delete"),
    path(
        "cards/<int:pk>/statements/<int:year>/<int:month>/",
        views.card_statement,
        name="card-statement",
    ),
    path("purchases/", views.purchase_list, name="purchases"),
    path("purchases/new/", views.purchase_create, name="purchase-create"),
    path("purchases/<int:pk>/", views.purchase_detail, name="purchase-detail"),
    path("purchases/<int:pk>/delete/", views.purchase_delete, name="purchase-delete"),
    path("purchases/<int:pk>/regenerate/", views.purchase_regenerate, name="purchase-regenerate"),
    path("payables/", views.payables_list, name="payables"),
    path("payables/generate/", views.payables_generate, name="payables-generate"),
    path("payables/recurring/<int:pk>/pay/", views.payables_recurring_pay, name="payables-recurring-pay"),
    path("recurring/", views.recurring_list, name="recurring"),
    path("recurring/new/", views.recurring_create, name="recurring-create"),
    path("recurring/<int:pk>/edit/", views.recurring_edit, name="recurring-edit"),
    path("recurring/<int:pk>/delete/", views.recurring_delete, name="recurring-delete"),
    path("recurring/<int:pk>/generate/", views.recurring_generate, name="recurring-generate"),
    path("recurring/instances/", views.recurring_instances, name="recurring-instances"),
    path("recurring/instances/<int:pk>/pay/", views.recurring_instance_pay, name="recurring-instance-pay"),
    path("recurring/instances/<int:pk>/value/", views.recurring_instance_value, name="recurring-instance-value"),
    path("import/", views.import_start, name="import-start"),
    path("import/parse/", views.import_parse, name="import-parse"),
    path("import/<int:pk>/review/", views.import_review, name="import-review"),
    path("import/<int:pk>/confirm/", views.import_confirm, name="import-confirm"),
    path("investments/", views.investments_list, name="investments"),
    path("investments/summary/", views.investments_summary, name="investments-summary"),
    path("investments/accounts/new/", views.investment_account_create, name="investment-account-create"),
    path("investments/accounts/<int:pk>/edit/", views.investment_account_edit, name="investment-account-edit"),
    path("investments/accounts/<int:pk>/delete/", views.investment_account_delete, name="investment-account-delete"),
    path("investments/snapshots/new/", views.investment_snapshot_create, name="investment-snapshot-create"),
    path(
        "investments/snapshots/<int:pk>/edit/",
        views.investment_snapshot_edit,
        name="investment-snapshot-edit",
    ),
    path(
        "investments/snapshots/<int:pk>/delete/",
        views.investment_snapshot_delete,
        name="investment-snapshot-delete",
    ),
    path("stats/annual/", views.annual_stats, name="annual-stats"),
    path("stats/annual/summary/", views.annual_stats_summary, name="annual-stats-summary"),
    path("categories/", views.category_list, name="categories"),
    path("categories/new/", views.category_create, name="category-create"),
    path("categories/<int:pk>/edit/", views.category_edit, name="category-edit"),
    path("categories/<int:pk>/delete/", views.category_delete, name="category-delete"),
    path("accounts/", views.account_list, name="accounts"),
    path("accounts/new/", views.account_create, name="account-create"),
    path("accounts/<int:pk>/edit/", views.account_edit, name="account-edit"),
    path("accounts/<int:pk>/delete/", views.account_delete, name="account-delete"),
    path("entries/", views.entry_list, name="entries"),
    path("entries/new/", views.entry_create, name="entry-create"),
    path("entries/<int:pk>/edit/", views.entry_edit, name="entry-edit"),
    path("entries/<int:pk>/delete/", views.entry_delete, name="entry-delete"),
    path("receivables/", views.receivable_list, name="receivables"),
    path("receivables/new/", views.receivable_create, name="receivable-create"),
    path("receivables/<int:pk>/edit/", views.receivable_edit, name="receivable-edit"),
    path("receivables/<int:pk>/delete/", views.receivable_delete, name="receivable-delete"),
    path("receivables/<int:pk>/receive/", views.receivable_receive, name="receivable-receive"),
    path("receivables/<int:pk>/cancel/", views.receivable_cancel, name="receivable-cancel"),
]
